# The path of the project you want to monitor (has to be full path, for OSX, Linux users ~ does not work)
path_to_monitor:

# The boardgamearena ftp site.
sftp_site:

# The path of your game on the boardgamearena ftp site
sftp_path:

# An exclusion list of the
exclusion_list: []